[package]
name = "y23d17"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools.workspace = true
criterion = "0.5.1"
pathfinding = "4.6.0"


[[bench]]
name = "y23d17"
path = "benches/y23d17.rs"
harness = false
