[package]
name = "advent_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = { workspace = true }
tracing = { workspace = true }
glam = { workspace = true }
nom = { workspace = true }
thiserror = "2.0.6"
array-init = "2.1.0"
