[package]
name = "y24d24"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
advent_utils.workspace = true
itertools.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
tracing-chrome.workspace = true
fxhash = "0.2.1"

[dev-dependencies]
divan.workspace = true

[[bench]]
name = "y24d24"
path = "benches/y24d24.rs"
harness = false
