[package]
name = "y23d23"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools.workspace = true
criterion = "0.5.1"
glam = "0.25.0"
pathfinding = "4.6.0"

[[bench]]
name = "y23d23"
path = "benches/y23d23.rs"
harness = false
