[package]
name = "y23d21"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools.workspace = true
criterion.workspace = true
rstest.workspace = true


[[bench]]
name = "y23d21"
path = "benches/y23d21.rs"
harness = false
