[package]
name = "y24d05"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools.workspace = true
nom.workspace = true
criterion.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true


[[bench]]
name = "y24d05"
path = "benches/y24d05.rs"
harness = false
