[package]
name = "y24d07"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
criterion.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true


[[bench]]
name = "y24d07"
path = "benches/y24d07.rs"
harness = false
