[package]
name = "y23d24"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools.workspace = true
rstest.workspace = true
rand = "0.8.4"
glam = "0.25.0"
criterion.workspace = true


[[bench]]
name = "y23d24"
path = "benches/y23d24.rs"
harness = false
